version: '3'

services:
    app:
        build: ./docker/apache
        ports:
            - 8082:80
        volumes:
            - ./www:/var/www/html
        links:
            - db_lesson:postgres

    db_lesson:
        image: postgres:13 # set version to 9 if you encounter problems.
        volumes:
            - pg-data-bdd:/var/log/postgresql
            - pg-data-bdd:/var/lib/postgresql/data
            - ./recupauto.sql:/docker-entrypoint-initdb.d/recupauto.sql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=cnam2021
            - POSTGRES_USER=postgres@test.com
            - POSTGRES_DB=recupauto

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: paulfauconnier@icloud.com
            PGADMIN_DEFAULT_PASSWORD: test123123
            PG_DATABASE: recupauto
            PG_USER: postgres@test.com
            PG_PASSWORD: cnam2021
        volumes:
            - ./docker/pgadmin:/root/.pgadmin
        ports:
            - 8081:80
        links:
            - db_lesson:postgres


volumes:
    pg-data-bdd: